import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, Archive, BadgeCheck, BookOpen, Brain, Briefcase, CalendarDays, Compass, Database, Download, FileUp, Layers3, Lightbulb, LogOut, Map, Rocket, Search, Settings, Sparkles, Target} from 'lucide-react';
import {get, login, post, uploadEvidence} from './api';
import './index.css';

type Module = 'Mission Control'|'Projects'|'Career'|'Capabilities'|'FGAs'|'Evidence'|'AI Workspace'|'Knowledge Vault'|'Decisions'|'Weekly Review'|'Global Search'|'Timeline'|'Backup / Export'|'Settings';
type AnyRecord = Record<string, any>;
const modules:{name:Module;icon:React.ElementType;sub:string}[]=[
{name:'Mission Control',icon:Compass,sub:'Command picture'},{name:'Projects',icon:Layers3,sub:'Execution'},{name:'Career',icon:Briefcase,sub:'Opportunities'},{name:'Capabilities',icon:BadgeCheck,sub:'Growth atlas'},{name:'FGAs',icon:Target,sub:'Focused growth'},{name:'Evidence',icon:Archive,sub:'Proof archive'},{name:'AI Workspace',icon:Brain,sub:'Prompts'},{name:'Knowledge Vault',icon:BookOpen,sub:'Notes'},{name:'Decisions',icon:Lightbulb,sub:'Traceability'},{name:'Weekly Review',icon:CalendarDays,sub:'Review engine'},{name:'Global Search',icon:Search,sub:'Find anything'},{name:'Timeline',icon:Activity,sub:'Activity'},{name:'Backup / Export',icon:Database,sub:'Local resilience'},{name:'Settings',icon:Settings,sub:'Local config'}];
const templates:Record<string,AnyRecord>={Projects:{name:'',objective:'',status:'active',priority:'medium'},Career:{company:'',role:'',salary:'',status:'found',capability_fit:0,evidence_fit:0,resume_fit:0,interview_fit:0,notes:''},Capabilities:{name:'',description:'',score:0,growth_history:''},FGAs:{name:'',goal:'',outcome:'',completed:false,evidence_generated:false,portfolio_value:'',reflection:'',capability_id:null},'AI Workspace':{title:'',item_type:'prompt',model:'',content:'',outcome:'',tags:''},'Knowledge Vault':{title:'',note_type:'note',content:'',tags:''},Decisions:{title:'',decision:'',rationale:'',consequences:'',project_id:null}};
const paths:Record<string,string>={Projects:'/projects',Career:'/opportunities',Capabilities:'/capabilities',FGAs:'/fgas','AI Workspace':'/ai-items','Knowledge Vault':'/notes',Decisions:'/decisions'};
const textareas=['objective','description','notes','goal','outcome','reflection','content','decision','rationale','consequences','summary','growth_history'];
function labelize(k:string){return k.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function color(v?:string){const s=(v||'').toLowerCase(); if(['complete','completed','offer'].includes(s))return'badge-green'; if(['blocked','rejected'].includes(s))return'badge-red'; if(['high','in_progress','interview','assessment'].includes(s))return'badge-amber'; if(['active','found','applied'].includes(s))return'badge-gold'; return'badge-blue'}
function Badge({children,c}:{children:React.ReactNode;c?:string}){return <span className={`badge ${c||'badge-gold'}`}>{children}</span>}
function Field({label,value,onChange,textarea=false,type='text'}:{label:string;value:any;onChange:(v:any)=>void;textarea?:boolean;type?:string}){const v=value??'';return <label className="block text-sm text-slate-300"><span>{labelize(label)}</span>{textarea?<textarea className="field min-h-24" value={v} onChange={e=>onChange(e.target.value)}/>:<input className="field" type={type} value={v} onChange={e=>onChange(type==='number'?Number(e.target.value):e.target.value)}/>}</label>}
function Progress({label,value}:{label:string;value:number}){const v=Math.max(0,Math.min(100,Number(value)||0));return <div><div className="flex justify-between text-xs text-slate-400 mb-1"><span>{label}</span><span>{v}%</span></div><div className="h-2 rounded-full bg-black/30 overflow-hidden"><div className="h-full rounded-full" style={{width:`${v}%`,background:'linear-gradient(90deg,#d6a84f,#f4d28a)'}}/></div></div>}
function Login({onDone}:{onDone:()=>void}){const[u,setU]=useState('reme'),[p,setP]=useState('quintessence-local'),[err,setErr]=useState('');return <main className="min-h-screen observatory-bg grid place-items-center p-6"><section className="max-w-3xl w-full text-center"><div className="flex justify-center mb-8"><div className="compass"><span/></div></div><h1 className="serif text-6xl md:text-7xl font-semibold text-white mb-4">Quintessence</h1><p className="text-xl text-blue-100 mb-8">Local personal operations, evidence, and capability command system.</p><div className="glass rounded-3xl p-6 max-w-md mx-auto text-left"><Field label="Username" value={u} onChange={setU}/><div className="h-3"/><Field label="Password" type="password" value={p} onChange={setP}/>{err&&<p className="text-red-300 text-sm mt-3">{err}</p>}<button className="btn-primary w-full mt-6" onClick={async()=>{try{await login(u,p);onDone()}catch(e:any){setErr(e.message)}}}>Enter Mission Control</button></div></section></main>}
function Title({module,action}:{module:Module;action?:React.ReactNode}){const m=modules.find(x=>x.name===module)!;const Icon=m.icon;return <div className="mb-6"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><div className="flex items-center gap-3 text-amber-200 mb-2"><Icon size={22}/><span className="tracking-[.22em] uppercase text-xs">{m.sub}</span></div><h2 className="serif text-4xl md:text-5xl font-semibold text-white">{module}</h2></div>{action}</div><div className="gold-line mt-5"/></div>}
function Empty({t,d}:{t:string;d:string}){return <div className="card p-8 text-center text-slate-300"><Sparkles className="mx-auto mb-3 text-amber-200"/><div className="font-bold text-white text-lg">{t}</div><p>{d}</p></div>}
function SimpleCard({module,item}:{module:Module;item:AnyRecord}){if(module==='Career')return <article className="card p-5"><div className="flex justify-between"><div><h3 className="text-xl font-bold">{item.role}</h3><p className="text-amber-100">{item.company}</p></div><Badge c={color(item.status)}>{item.status}</Badge></div><div className="grid md:grid-cols-2 gap-3 mt-4"><Progress label="Capability" value={item.capability_fit}/><Progress label="Evidence" value={item.evidence_fit}/><Progress label="Resume" value={item.resume_fit}/><Progress label="Interview" value={item.interview_fit}/></div>{item.notes&&<p className="text-slate-300 mt-4">{item.notes}</p>}</article>;
if(module==='Capabilities')return <article className="card p-5"><div className="flex justify-between"><h3 className="text-xl font-bold">{item.name}</h3><Badge>Score {item.score}</Badge></div><p className="text-slate-300 mt-3">{item.description||'No description yet.'}</p><Progress label="Current score" value={item.score}/></article>;
if(module==='FGAs')return <article className="card p-5"><div className="flex justify-between"><h3 className="text-xl font-bold">{item.name}</h3><Badge c={item.completed?'badge-green':'badge-amber'}>{item.completed?'Complete':'Active'}</Badge></div><p className="text-slate-300 mt-3">{item.goal||'No goal captured yet.'}</p>{item.reflection&&<p className="card-soft p-3 mt-4 text-sm">{item.reflection}</p>}</article>;
if(module==='Decisions')return <article className="card p-5"><h3 className="text-xl font-bold">{item.title}</h3><p className="mt-3"><b className="text-amber-200">Decision:</b> {item.decision}</p>{item.rationale&&<p className="text-slate-300 mt-2"><b>Rationale:</b> {item.rationale}</p>}</article>;
return <article className="card p-5"><div className="flex justify-between gap-4"><h3 className="text-xl font-bold">{item.name||item.title}</h3>{item.status&&<Badge c={color(item.status)}>{item.status}</Badge>}</div><p className="text-slate-300 mt-3 whitespace-pre-wrap">{item.objective||item.description||item.content||item.goal||item.outcome||'No detail captured yet.'}</p></article>}
function Resource({module}:{module:Exclude<Module,'Mission Control'|'Evidence'|'Weekly Review'|'Global Search'|'Timeline'|'Backup / Export'|'Settings'>}){const[items,setItems]=useState<AnyRecord[]>([]),[form,setForm]=useState<AnyRecord>({...templates[module]}),[q,setQ]=useState(''),[open,setOpen]=useState(true);async function load(){setItems(await get(paths[module]))}useEffect(()=>{load()},[module]);const filtered=useMemo(()=>items.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())),[items,q]);return <section><Title module={module} action={<button className="btn-primary" onClick={()=>setOpen(!open)}>{open?'Hide capture':'Quick capture'}</button>}/>{open&&<div className="card p-5 mb-5"><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{Object.keys(templates[module]).map(k=><Field key={k} label={k} value={form[k]} onChange={v=>setForm({...form,[k]:v})} textarea={textareas.includes(k)} type={typeof templates[module][k]==='number'?'number':'text'}/>)}</div><button className="btn-primary mt-4" onClick={async()=>{await post(paths[module],form);setForm({...templates[module]});load()}}>Add to {module}</button></div>}<SearchBar q={q} setQ={setQ}/>{filtered.length?<div className="grid xl:grid-cols-2 gap-4">{filtered.map(x=><SimpleCard key={x.id} module={module} item={x}/>)}</div>:<Empty t={`No ${module.toLowerCase()} yet`} d="Capture the first item above."/>}</section>}
function SearchBar({q,setQ}:{q:string;setQ:(v:string)=>void}){return <div className="card p-3 flex gap-2 items-center mb-5"><Search size={18} className="text-amber-200"/><input className="bg-transparent outline-none text-white flex-1" placeholder="Search locally..." value={q} onChange={e=>setQ(e.target.value)}/></div>}
function Dashboard(){const[d,setD]=useState<any>(null);useEffect(()=>{get('/dashboard').then(setD)},[]);if(!d)return <p>Loading...</p>;const metrics=[['Active Projects',d.active_projects,Layers3],['Active FGAs',d.active_fgas,Target],['Opportunities',d.opportunities,Briefcase],['Evidence',d.evidence_generated,Archive]];return <section><Title module="Mission Control" action={<Badge>Local-only</Badge>}/><div className="grid md:grid-cols-4 gap-4 mb-6">{metrics.map(([l,v,I]:any)=><div className="card p-5" key={l}><I className="text-amber-200 mb-4"/><p className="text-slate-400 text-sm">{l}</p><p className="serif text-5xl text-white">{v}</p></div>)}</div><div className="grid xl:grid-cols-3 gap-5"><Panel title="Blocked work" items={d.blocked_tasks}/><Panel title="Recent evidence" items={d.recent_evidence}/><Panel title="Recent decisions" items={d.recent_decisions}/></div></section>}
function Panel({title,items}:{title:string;items:AnyRecord[]}){return <div className="card p-5"><h3 className="text-lg font-bold text-amber-100 mb-4">{title}</h3>{items?.length?<div className="space-y-3">{items.map(x=><div key={x.id} className="card-soft p-3"><div className="font-semibold">{x.title||x.name}</div><p className="text-sm text-slate-400">{x.summary||x.decision||x.status||x.objective}</p></div>)}</div>:<p className="text-slate-400">Nothing here right now.</p>}</div>}
function Evidence(){const[items,setItems]=useState<AnyRecord[]>([]),[file,setFile]=useState<File|null>(null),[form,setForm]=useState({title:'',summary:'',evidence_type:'artifact',tags:''}),[q,setQ]=useState('');async function load(){setItems(await get('/evidence'))}useEffect(()=>{load()},[]);const filtered=items.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase()));return <section><Title module="Evidence" action={<Badge c="badge-green">Evidence Engine</Badge>}/><div className="card p-5 mb-5"><div className="grid md:grid-cols-2 gap-4"><Field label="title" value={form.title} onChange={v=>setForm({...form,title:v})}/><Field label="evidence_type" value={form.evidence_type} onChange={v=>setForm({...form,evidence_type:v})}/><Field label="tags" value={form.tags} onChange={v=>setForm({...form,tags:v})}/><label className="text-sm text-slate-300">Local file<input className="field text-white bg-black/20" type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><div className="md:col-span-2"><Field label="summary" value={form.summary} onChange={v=>setForm({...form,summary:v})} textarea/></div></div><button className="btn-primary mt-4" onClick={async()=>{if(file){const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.append(k,String(v)));fd.append('file',file);await uploadEvidence(fd)}else await post('/evidence',{...form,capability_ids:[],project_ids:[],task_ids:[],fga_ids:[],opportunity_ids:[]});setForm({title:'',summary:'',evidence_type:'artifact',tags:''});setFile(null);load()}}><FileUp className="inline mr-2" size={18}/>Capture Evidence</button></div><SearchBar q={q} setQ={setQ}/><div className="grid xl:grid-cols-2 gap-4">{filtered.map(e=><article key={e.id} className="card p-5"><div className="flex justify-between"><h3 className="text-xl font-bold">{e.title}</h3><Badge>{e.evidence_type}</Badge></div><p className="text-slate-300 mt-3">{e.summary||'No summary yet.'}</p><div className="mt-4"><Progress label="Evidence completeness" value={e.evidence_score}/><p className="text-xs text-slate-400 mt-2">{e.completeness_notes}</p></div><div className="grid gap-3 mt-4"><TextBlock title="Resume bullet" text={e.resume_bullet_draft}/><TextBlock title="STAR story" text={e.star_story_draft||e.interview_story_draft}/></div>{e.file_path&&<p className="text-xs text-slate-500 mt-3">Stored: {e.file_path}</p>}</article>)}</div></section>}
function TextBlock({title,text}:{title:string;text:string}){return <div className="card-soft p-3"><div className="text-xs uppercase text-amber-200 tracking-wider mb-1">{title}</div><p className="whitespace-pre-wrap text-slate-200">{text}</p></div>}
function Weekly(){const[w,setW]=useState<any>(null),[hist,setHist]=useState<any[]>([]);async function load(){setW(await get('/weekly-review'));setHist(await get('/weekly-reviews'))}useEffect(()=>{load()},[]);if(!w)return <p>Loading...</p>;return <section><Title module="Weekly Review" action={<button className="btn-primary" onClick={async()=>{await post('/weekly-review/save',{title:'Weekly Review',notes:''});load()}}>Save snapshot</button>}/><div className="grid xl:grid-cols-2 gap-5"><Panel title="Completed work" items={w.completed_work}/><Panel title="Blockers" items={w.blockers}/><Panel title="Evidence generated" items={w.evidence_generated}/><div className="card p-5"><h3 className="text-lg font-bold text-amber-100 mb-4">Recommended next actions</h3>{w.recommended_next_actions?.map((x:string)=><div className="card-soft p-3 mb-2" key={x}>{x}</div>)}</div></div><h3 className="serif text-3xl mt-8 mb-4">Archive</h3><div className="grid gap-3">{hist.map(h=><div className="card p-4" key={h.id}><b>{h.title}</b><p className="text-slate-400 text-sm">{h.created_at}</p></div>)}</div></section>}
function GlobalSearch(){const[q,setQ]=useState(''),[res,setRes]=useState<any[]>([]);useEffect(()=>{if(q.length>1)get('/search?q='+encodeURIComponent(q)).then(setRes);else setRes([])},[q]);return <section><Title module="Global Search"/><SearchBar q={q} setQ={setQ}/><div className="grid gap-3">{res.map((r,i)=><div className="card p-4" key={i}><Badge>{r.module}</Badge><h3 className="font-bold mt-2">{r.title}</h3><p className="text-slate-400">{r.summary}</p></div>)}</div></section>}
function TimelinePage(){const[items,setItems]=useState<any[]>([]);useEffect(()=>{get('/activity').then(setItems)},[]);return <section><Title module="Timeline"/><div className="grid gap-3">{items.map(a=><div className="card p-4 flex gap-4" key={a.id}><Map className="text-amber-200 shrink-0"/><div><b>{a.action} {a.entity_type}</b><p className="text-slate-400">{a.summary}</p><p className="text-xs text-slate-500">{a.created_at}</p></div></div>)}</div></section>}
function BackupExport(){const[msg,setMsg]=useState(''),[paths,setPaths]=useState<any>({});useEffect(()=>{get('/local/paths').then(setPaths)},[]);return <section><Title module="Backup / Export"/><div className="grid md:grid-cols-2 gap-4"><Action icon={Database} title="Create backup" detail="Backs up SQLite data and local evidence storage." onClick={async()=>setMsg(JSON.stringify(await post('/backup/create',{}),null,2))}/><Action icon={Download} title="Create export" detail="Exports JSON, CSV, and resume bullet markdown." onClick={async()=>setMsg(JSON.stringify(await post('/export/create',{}),null,2))}/></div><div className="card p-5 mt-5"><h3 className="font-bold text-amber-100 mb-2">Local paths</h3><pre className="text-sm text-slate-300 whitespace-pre-wrap">{JSON.stringify(paths,null,2)}</pre>{msg&&<pre className="mt-4 card-soft p-3 text-sm whitespace-pre-wrap">{msg}</pre>}</div></section>}
function Action({icon:Icon,title,detail,onClick}:{icon:React.ElementType;title:string;detail:string;onClick:()=>void}){return <button onClick={onClick} className="card p-5 text-left hover:border-amber-300/40"><Icon className="text-amber-200 mb-3"/><h3 className="text-xl font-bold">{title}</h3><p className="text-slate-400">{detail}</p></button>}
function SettingsPage(){const[items,setItems]=useState<any[]>([]);useEffect(()=>{get('/settings').then(setItems)},[]);return <section><Title module="Settings"/><div className="grid gap-3">{items.map(s=><div className="card p-4" key={s.key}><div className="text-amber-200 font-bold">{s.key}</div><div className="text-slate-300">{s.value}</div></div>)}</div></section>}
function App(){const[authed,setAuthed]=useState(!!localStorage.getItem('quint_token')), [mod,setMod]=useState<Module>('Mission Control');if(!authed)return <Login onDone={()=>setAuthed(true)}/>;return <div className="min-h-screen observatory-bg flex"><aside className="w-72 p-4 border-r border-amber-200/10 bg-black/20 backdrop-blur-xl hidden md:block"><div className="flex items-center gap-3 mb-7"><div className="compass scale-75"><span/></div><div><h1 className="serif text-2xl">Quintessence</h1><p className="text-xs text-slate-500">Local operating system</p></div></div><nav className="grid gap-1">{modules.map(m=>{const I=m.icon;return <button key={m.name} className={`nav-item ${mod===m.name?'nav-active':''}`} onClick={()=>setMod(m.name)}><I size={18}/><span><span className="block">{m.name}</span><span className="text-xs opacity-60">{m.sub}</span></span></button>})}</nav><button className="mt-6 flex gap-2 text-slate-500 hover:text-white" onClick={()=>{localStorage.removeItem('quint_token');location.reload()}}><LogOut size={16}/>Log out</button></aside><main className="flex-1 p-5 md:p-8 overflow-auto">{mod==='Mission Control'?<Dashboard/>:mod==='Evidence'?<Evidence/>:mod==='Weekly Review'?<Weekly/>:mod==='Global Search'?<GlobalSearch/>:mod==='Timeline'?<TimelinePage/>:mod==='Backup / Export'?<BackupExport/>:mod==='Settings'?<SettingsPage/>:<Resource module={mod as any}/>}</main></div>}
createRoot(document.getElementById('root')!).render(<App/>);
